pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps {
        git 'https://github.com/Deeps-05/awesome-compose.git'
      }
    }
    stage('Build and Run') {
      steps {
        dir('official-documentation-samples/django') {
          // All commands here run inside that subfolder
          sh 'docker-compose up -d --build'
        }
      }
    }
  }
}
